---
title: "Lab 06 - Functions and iterations"
author: "Ethan Avigdor"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}

diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )

```


## Exercise 1

```{r}


diamonds%>%group_by(color)%>%summarise(mean_carat=mean(carat),
                                       mean_price=mean(price),
                                       mean_table_pct=mean(table_pct))

diamonds%>%group_by(clarity)%>%summarise(mean_carat=mean(carat),
                                       mean_price=mean(price),
                                       mean_table_pct=mean(table_pct))

diamonds%>%group_by(cut)%>%summarise(mean_carat=mean(carat),
                                       mean_price=mean(price),
                                  mean_table_pct=mean(table_pct))


```


## Exercise 2

```{r}



# Overall table_mm arithmetic mean?
diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)
diamonds%>%summarise(mean_table_mm=mean(table_mm))



# table_mm arithmetic mean within each clarity category


diamonds%>%group_by(clarity)%>%summarise(mean_table_mm=mean(table_mm))
#mean table_mm is inversely proportional to the clarity of the  diamonds so the lowest clarity has the highest average table_mm and the highest clarity has the lowest average table_mm


```

_Add your comment here_

```{r}
# calculate the arithmetic mean across all numeric variables




```

## Exercise 3

```{r}
# Write gmean() command



```

## Exercise 4

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples


```


## Exercise 5

```{r}
# Copy gmean() from Ex 3 and edit it to check the input





# Copy your code from Ex 4 to test your new command





```

## Exercise 6

```{r}
# replicate the for loop from Ex 4 using the map (or a similar) function

```


## Exercise 7

```{r}
# Overall table_mm arithmetic mean, median, and geometric mean?






# Arithmetic mean, median, and geometric mean of table_mm within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```

## Exercise 10 (optional)

_Do derivation on paper, unless you know how to write LaTeX code_
